name: Actualizar Estadísticas de GitHub

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

# Otorgamos permisos para que el bot pueda hacer push
permissions:
  contents: write

jobs:
   steps:
      # 1. Descargamos el código de tu repositorio a la máquina virtual
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2. Corremos la librería oficial local que genera tu nueva gráfica
      - name: Generar Métricas del Perfil
        uses: lowlighter/metrics@latest
        with:
          # Llamamos al secreto que acabas de guardar con éxito
          token: ${{ secrets.METRICS_TOKEN }}
          
          # Tu nombre de usuario de GitHub
          user: freneklopez
          
          # Estilo clásico y limpio
          template: classic
          
          # Datos que se van a procesar e incluir en el diseño
          base: header, activity, community, repositories, metadata
          
          # Tu zona horaria para que calcule los datos con precisión
          config_timezone: America/Tijuana
          
          # Nombre del archivo SVG que va a generar en tu repositorio
          filename: github-metrics.svg

      # 3. Guardamos el archivo generado directamente en tu repositorio
      - name: Guardar cambios en el repositorio
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action Bot"
          git add github-metrics.svg
          git diff-index --quiet HEAD || git commit -m "docs: Actualizar métricas del perfil automáticamente [skip ci]"
          git push
